name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Dump env
      run: echo ${GITHUB_WORKSPACE}

    - name: Decrypt android key store
      run:  openssl enc -aes-256-cbc -d -K ${{ secrets.K }} -iv ${{ secrets.IV }} -in ${GITHUB_WORKSPACE}/environment/keys/android-key-enc -out ${GITHUB_WORKSPACE}/environment/keys/android.jks

    - name: build
      uses: xdtianyu/actions-android-ci@master
      with: 
        args: '"
        source .travis/env.sh;
        source /opt/setup-android-sdk.sh;
        export KEYSTORE_PASS=${{ secrets.KEYSTORE_PASS }};
        export ALIAS_NAME=${{ secrets.ALIAS_NAME }};
        export ALIAS_PASS=${{ secrets.ALIAS_PASS }};
        ./build_debug.sh
        "'
        
    - name: Publish
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: 'app_*.apk'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
